name: Build and Deploy Container App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: latest
        cli_config_credentials_token: ${{ secrets.TF_CLOUD_TOKEN }}

    - name: Terraform Init
      id: init
      run: terraform -chdir="./iac" init

    - name: Terraform Validate
      id: validate
      run: terraform -chdir="./iac" validate

    - name: Terraform Plan
      id: plan
      run: terraform -chdir="./iac" plan
      continue-on-error: true

    - name: Terraform Plan Status
      if: steps.plan.outcome == 'failure'
      run: exit 1

    - name: Terraform Apply
      run: terraform -chdir="./iac" apply -auto-approve

    - name: Capture Terraform Outputs
      id: terraform_outputs
      run: |
        echo "::set-env name=OUTPUT_VAR_1::$(terraform -chdir='./iac' output -raw output_var_1)"
        echo "::set-env name=OUTPUT_VAR_2::$(terraform -chdir='./iac' output -raw output_var_2)"
    - name: Display Terraform Outputs
      run: |
        echo "Output 1: $OUTPUT_VAR_1"
        echo "Output 2: $OUTPUT_VAR_2"
    - uses: azure/docker-login@v1
      with:
        login-server: lalithrgdevacr.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - run: |
        docker build . -t lalithrgdevacr.azurecr.io/myapp:1.0.0
        docker push lalithrgdevacr.azurecr.io/myapp:1.0.0
